# Generated by Django 3.0.7 on 2020-07-04 10:39

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
            ],
        ),
        migrations.CreateModel(
            name='Binging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Тип переплёта')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название Жанра')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание Жанра')),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя книги')),
                ('picture', models.ImageField(blank=True, default='books-pic/default.jpg', null=True, upload_to='books-pic', verbose_name='Фото обложки')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Цена')),
                ('publishing_year', models.PositiveSmallIntegerField(default=2020, verbose_name='Год издания')),
                ('count_page', models.IntegerField(default=100, verbose_name='Кол-во страниц')),
                ('format_book', models.CharField(default='99x99', max_length=15, verbose_name='Формат')),
                ('isbn', models.CharField(default='999-1-88877-6', max_length=20, verbose_name='ISBN')),
                ('weight', models.PositiveSmallIntegerField(default='100', verbose_name='Вес(гр.)')),
                ('age_limit', models.CharField(default='6+', max_length=3, verbose_name='Ограничение по возрасту')),
                ('count_book', models.IntegerField(default=10, verbose_name='Ко-во книг в наличии')),
                ('availability', models.BooleanField(default=True, verbose_name='Наличие книги')),
                ('rating', models.FloatField(default=9, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Рейтинг')),
                ('create', models.DateField(auto_now_add=True, verbose_name='Дата внесения в каталог')),
                ('update', models.DateField(auto_now=True, verbose_name='Дата последнего изменения')),
                ('author', models.ManyToManyField(to='books.Author', verbose_name='Автор')),
                ('binging', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='books.Binging', verbose_name='Переплёт')),
                ('genre', models.ManyToManyField(to='books.Genre', verbose_name='Жанр')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
