# Generated by Django 3.0.7 on 2020-06-16 18:22

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='age_limit',
            field=models.CharField(default='6+', max_length=3, verbose_name='Ограничение по возрасту'),
        ),
        migrations.AddField(
            model_name='books',
            name='count_book',
            field=models.IntegerField(default=10, verbose_name='Ко-во книг в наличии'),
        ),
        migrations.AddField(
            model_name='books',
            name='create',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2020, 6, 16, 18, 22, 0, 452715, tzinfo=utc), verbose_name='Дата внесения в каталог'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='books',
            name='format_book',
            field=models.CharField(default='99x99', max_length=15, verbose_name='Формат'),
        ),
        migrations.AddField(
            model_name='books',
            name='isbn',
            field=models.CharField(default='999-1-88877-6', max_length=20, verbose_name='ISBN'),
        ),
        migrations.AddField(
            model_name='books',
            name='rating',
            field=models.IntegerField(default=9, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Рейтинг'),
        ),
        migrations.AddField(
            model_name='books',
            name='update',
            field=models.DateField(auto_now=True, verbose_name='Дата последнего изменения'),
        ),
        migrations.AddField(
            model_name='books',
            name='weight',
            field=models.PositiveSmallIntegerField(default='100', verbose_name='Вес(гр.)'),
        ),
        migrations.AlterField(
            model_name='books',
            name='publishing_year',
            field=models.PositiveSmallIntegerField(default=2020, verbose_name='Год издания'),
        ),
    ]
