# Generated by Django 3.0.7 on 2020-07-13 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание книги'),
        ),
        migrations.AlterField(
            model_name='books',
            name='isbn',
            field=models.CharField(default='999-1-88877-6', max_length=15, verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='books',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
