# Generated by Django 3.0.7 on 2020-07-15 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20200713_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='author',
            field=models.ManyToManyField(related_name='author', to='books.Author', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='books',
            name='genre',
            field=models.ManyToManyField(related_name='genre', to='books.Genre', verbose_name='Жанр'),
        ),
    ]
