# Generated by Django 3.0.7 on 2020-06-16 20:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20200616_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='rating',
            field=models.FloatField(default=9, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Рейтинг'),
        ),
    ]
