# Generated by Django 3.0.7 on 2020-07-15 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20200715_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='author',
            field=models.ManyToManyField(related_name='books_author', to='books.Author', verbose_name='Автор'),
        ),
    ]
