# Generated by Django 3.0.7 on 2020-06-17 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_books_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='number_page',
            new_name='count_page',
        ),
    ]
