# Generated by Django 3.0.7 on 2020-07-15 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20200715_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='genre',
            field=models.ManyToManyField(related_name='genre_books', to='books.Genre', verbose_name='Жанр'),
        ),
    ]
