# Generated by Django 3.0.7 on 2020-06-17 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_books_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='lastn_name',
            new_name='last_name',
        ),
    ]
