# Generated by Django 3.0.7 on 2020-07-16 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_publisher_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='series',
            field=models.ManyToManyField(related_name='series_books', to='books.Series', verbose_name='Серия'),
        ),
    ]
