# Generated by Django 3.0.7 on 2020-06-18 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_auto_20200617_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='picture',
            field=models.ImageField(blank=True, default='books-pic/default.jpg', null=True, upload_to='books-pic', verbose_name='Фото обложки'),
        ),
    ]
