# Generated by Django 3.0.7 on 2020-07-16 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_books_series'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='series',
            field=models.ManyToManyField(blank=True, null=True, related_name='series_books', to='books.Series', verbose_name='Серия'),
        ),
    ]
