# Generated by Django 3.0.7 on 2020-07-19 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_books_publisher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя книги'),
        ),
    ]
