# Generated by Django 3.0.7 on 2020-07-23 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_auto_20200719_2041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='create',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='update',
            new_name='updated',
        ),
        migrations.AlterField(
            model_name='books',
            name='count_book',
            field=models.IntegerField(default=100, verbose_name='Ко-во книг в наличии'),
        ),
    ]
