# Generated by Django 3.0.7 on 2020-07-24 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_auto_20200724_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='series',
            field=models.ManyToManyField(blank=True, related_name='series_books', to='books.Series', verbose_name='Серия'),
        ),
    ]
