# Generated by Django 3.0.7 on 2020-07-24 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_auto_20200724_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='description',
            field=models.TextField(blank=True, default='Информация об авторескоро будет добавлена на сайт. Сделать ее более полной и интересной помогут объективные отзывы тех, кто хорошо знаком с творчеством и фактами биографии данного автора. Оставляйте свои комментарии, делитесь впечатлениями и вступайте в дискуссии — это поможет другим сделать выбор.', null=True, verbose_name='Информация об атворе'),
        ),
    ]
