# Generated by Django 3.0.7 on 2020-07-16 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0003_auto_20200716_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False, verbose_name='Статус заказа')),
                ('delivery_address', models.TextField(verbose_name='Адрес доставки')),
                ('contact_phone', models.CharField(max_length=50, verbose_name='Контактный номер')),
                ('create', models.DateField(auto_now_add=True, verbose_name='Дата cоздания')),
                ('update', models.DateField(auto_now=True, verbose_name='Дата последнего изменения')),
                ('cart', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='cart.Cart')),
            ],
        ),
    ]
