# Generated by Django 3.0.7 on 2020-07-19 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20200717_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='contact_phone',
            field=models.CharField(max_length=15, verbose_name='Контактный номер'),
        ),
    ]
