# Generated by Django 3.0.7 on 2020-07-22 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_status2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status2',
            field=models.CharField(choices=[('В обработке', 'В обработке'), ('Доставка', 'Доставка'), ('Отменен', 'Отменен'), ('Закрыт', 'Закрыт')], default='Открыт', max_length=100, verbose_name='Статус заказа'),
        ),
    ]
