# Generated by Django 3.0.7 on 2020-07-22 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_auto_20200723_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status2',
            field=models.CharField(choices=[('В обработке', 'В обработке'), ('Доставка', 'Доставка'), ('Отменен', 'Отменен'), ('Выполнен', 'Выполнен')], default='В обработке', max_length=100, verbose_name='Статус заказа'),
        ),
    ]
