# Generated by Django 3.0.7 on 2020-07-20 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedata',
            name='usd',
            field=models.FloatField(blank=True, null=True, verbose_name='USD'),
        ),
        migrations.AlterField(
            model_name='coursedata',
            name='create',
            field=models.DateField(verbose_name='Текущая дата'),
        ),
    ]
