# Generated by Django 3.0.7 on 2020-07-20 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0002_auto_20200720_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedata',
            name='eur',
            field=models.FloatField(blank=True, null=True, verbose_name='EUR'),
        ),
        migrations.AddField(
            model_name='coursedata',
            name='rub',
            field=models.FloatField(blank=True, null=True, verbose_name='RUB'),
        ),
    ]
