# Generated by Django 3.0.7 on 2020-07-07 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, default='375290000000', max_length=15, null=True, verbose_name='Телефон')),
                ('address_1', models.CharField(default='Беларусь', max_length=128, verbose_name='address')),
                ('address_2', models.CharField(blank=True, max_length=128, verbose_name='address')),
                ('city', models.CharField(default='Минск', max_length=64, verbose_name='Город')),
                ('county', models.CharField(default='Беларусь', max_length=64, verbose_name='Страна')),
                ('zip_code', models.CharField(default='23555', max_length=5, verbose_name='Почтовый индекс')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
