# Generated by Django 3.0.7 on 2020-07-07 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20200707_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address_1',
            field=models.CharField(blank=True, max_length=128, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, default='Минск', max_length=64, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='county',
            field=models.CharField(blank=True, default='Беларусь', max_length=64, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='zip_code',
            field=models.CharField(blank=True, default='23555', max_length=5, verbose_name='Почтовый индекс'),
        ),
    ]
