# Generated by Django 3.0.7 on 2020-07-07 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20200707_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, default='example@example.com', max_length=40, null=True, verbose_name='емаил'),
        ),
    ]
