# Generated by Django 3.0.6 on 2020-06-04 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_hello_word', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parser_log',
            name='update',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата обновления'),
        ),
    ]
