# Generated by Django 3.0.7 on 2020-06-14 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_hello_word', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Название Жанра'),
        ),
    ]
